In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from hmmlearn.hmm import GaussianHMM

n_states = 3

In [14]:
from datetime import datetime
from regimeaware.routines import cfg
import warnings
warnings.filterwarnings('ignore')

cfg.data_fldr = r"C:\Users\franc\My Drive\bin\regimeaware\data"
dt = datetime(2023, 12, 31)
X = pd.read_pickle(f'{cfg.data_fldr}/ff.pkl').loc[:dt, cfg.factor_set]

mdl = GaussianHMM(
    n_components=n_states,
    covariance_type="diag",
    random_state=cfg.hm_rs,
    min_covar=cfg.hm_min_covar,
    tol=cfg.hm_tol,
    implementation=cfg.hm_implementation
)
mdl.fit(X)

# Parameters
hm_mu = np.round(mdl.means_, 4)
hm_covars = np.round(mdl.covars_, 4)
hm_transmat = np.round(mdl.transmat_, 4)
hm_startprob = np.round(mdl.startprob_, 4)

print(hm_mu)
print(hm_covars)
print(hm_transmat)
print(hm_startprob)

[[ 0.0102  0.003  -0.0004  0.0027 -0.0003]
 [ 0.0384  0.0115 -0.0315 -0.0044 -0.0208]
 [-0.0306 -0.0063  0.0353  0.0073  0.0278]]
[[[0.0011 0.     0.     0.     0.    ]
  [0.     0.0006 0.     0.     0.    ]
  [0.     0.     0.0004 0.     0.    ]
  [0.     0.     0.     0.0002 0.    ]
  [0.     0.     0.     0.     0.0002]]

 [[0.0037 0.     0.     0.     0.    ]
  [0.     0.0029 0.     0.     0.    ]
  [0.     0.     0.002  0.     0.    ]
  [0.     0.     0.     0.0018 0.    ]
  [0.     0.     0.     0.     0.0007]]

 [[0.0031 0.     0.     0.     0.    ]
  [0.     0.0015 0.     0.     0.    ]
  [0.     0.     0.001  0.     0.    ]
  [0.     0.     0.     0.0012 0.    ]
  [0.     0.     0.     0.     0.0005]]]
[[0.8941 0.0326 0.0734]
 [0.3089 0.3903 0.3008]
 [0.2739 0.1894 0.5367]]
[1. 0. 0.]


In [ ]:
hm_mu = np.array([
    [0.0102,  0.003,  -0.0004,  0.0027, -0.0003],
    [0.0384,  0.0115, -0.0315, -0.0044, -0.0208],
    [-0.0306, -0.0063,  0.0353,  0.0073,  0.0278],
])

hm_covars = np.array([
    [
        [0.0011, 0.,     0.,     0.,     0.,    ],
        [0.,     0.0006, 0.,     0.,     0.,    ],
        [0.,     0.,     0.0004, 0.,     0.,    ],
        [0.,     0.,     0.,     0.0002, 0.,    ],
        [0.,     0.,     0.,     0.,     0.0002,],
    ],

    [
        [0.0037, 0.,     0.,     0.,     0.,    ],
        [0.,     0.0029, 0.,     0.,     0.,    ],
        [0.,     0.,     0.002,  0.,     0.,    ],
        [0.,     0.,     0.,     0.0018, 0.,    ],
        [0.,     0.,     0.,     0.,     0.0007,],
    ],

    [
        [0.0031, 0.,     0.,     0.,     0.,    ],
        [0.,     0.0015, 0.,     0.,     0.,    ],
        [0.,     0.,     0.001,  0.,     0.,    ],
        [0.,     0.,     0.,     0.0012, 0.,    ],
        [0.,     0.,     0.,     0.,     0.0005,],
    ]
])

hm_transmat = [
    [0.8941, 0.0326, 0.0734],
    [0.3089, 0.3903, 0.3008],
    [0.2739, 0.1894, 0.5367],
]

hm_startprob = np.array([1. 0. 0.])